spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebadb?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
server:
  servlet:
    context-path: /raiz